backend:
  name: github
  repo: 9punto5/docs-conferencia-2025
  branch: main

# Media files stored in repo
media_folder: "src/assets/images"
public_folder: "/src/assets/images"

# Collections define the content types
collections:
  - name: "planificacion-general"
    label: "📊 Planificación General"
    folder: "src/content/docs/01-planificacion-general"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "contenidos"
    label: "📝 Contenidos"
    folder: "src/content/docs/02-contenidos"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "roles-participantes"
    label: "👥 Roles de Participantes"
    folder: "src/content/docs/02-contenidos/roles-participantes"
    create: false
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "produccion"
    label: "🎬 Producción"
    folder: "src/content/docs/03-produccion"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "marketing"
    label: "📢 Marketing"
    folder: "src/content/docs/04-marketing"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "tecnologia"
    label: "💻 Tecnología"
    folder: "src/content/docs/05-tecnologia"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "sponsor"
    label: "💰 Sponsor"
    folder: "src/content/docs/06-sponsor"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "eventos"
    label: "🎪 Eventos"
    folder: "src/content/docs/07-eventos"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "evento-valdivia"
    label: "⭐ Valdivia (Principal)"
    folder: "src/content/docs/07-eventos/valdivia"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}

  - name: "recursos"
    label: "📚 Recursos"
    folder: "src/content/docs/08-recursos"
    create: true
    delete: false
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}